## Tensorflow API Examples

In [1]:
import tensorflow  as tf
import numpy as np

## tf.Session

A class for running TensorFlow operations. A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

In [2]:
matrix1 = tf.constant([[3, 3]]) 
matrix2 = tf.constant([[2],[2]]) 
product = tf.matmul(matrix1,matrix2)

# method 1 
sess = tf.Session() 
result = sess.run(product) 
print(result) 
sess.close() 
#[[12]] 

# method 2 
with tf.Session() as sess: 
    result2 = sess.run(product) 
    print(result2) 
#[[12]]


[[12]]
[[12]]


## tf.Variable

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. The initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

In [59]:
a1=tf.Variable(tf.random_normal(shape=[2,3], mean=0, stddev=1),name='a1')
a2=tf.Variable(tf.constant(1),name='a2')
a3=tf.Variable(tf.ones(shape=[2,3],name='a3'))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a1))
    print(sess.run(a2))
    print(sess.run(a3))

[[-1.0769126   0.8268242  -1.4716417 ]
 [-0.44789833  1.8247905  -1.4525865 ]]
1
[[1. 1. 1.]
 [1. 1. 1.]]


## tf.constant

Creates a constant tensor.

In [22]:
a = tf.constant(1)
b = tf.constant(2)
c = tf.constant(3)
d = tf.constant(4)
add1 = tf.add(a, b)
mul1 = tf.multiply(b, c)
add2 = tf.add(c, d)
output = tf.add(add1, mul1)

with tf.Session() as sess:
    print(sess.run(output))

9


## tf.placeholder

Inserts a placeholder for a tensor that will be always fed.

Important: This tensor will produce an error if evaluated. Its value must be fed using the feed_dict optional argument to Session.run(), Tensor.eval(), or Operation.run().

In [28]:
a = tf.placeholder(tf.float32, None, name='a')
b = tf.placeholder(tf.float32, None, name='b')
c = tf.multiply(a,b)
d = tf.add(a, b)
e = tf.add(c, d)
f = tf.Print(e, [a, b, c, d, e], message='This is a, b, c, d, e')

In [29]:
with tf.Session() as sess:
    print(sess.run(e, feed_dict={a:1, b:2}))

5.0


In [30]:
with tf.Session() as sess:
    sess.run(f, feed_dict={a:1, b:2})

## tf.ones, tf.zeros, tf.fill

tf.ones: Creates a tensor with all elements set to 1.

tf.zeros: Creates a tensor with all elements set to zero.

tf.fill: Creates a tensor filled with a scalar value.

In [94]:
matrix5 = tf.ones([3,4])
matrix6 = tf.zeros([4,3])
matrix7 = tf.fill([2,3],8)

with tf.Session() as sess:
    print(sess.run(matrix5))
    print(sess.run(matrix6))
    print(sess.run(matrix7))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[8 8 8]
 [8 8 8]]


## tf.get_variable

Gets an existing variable with these parameters or create a new one.

In [54]:
def foo():
  with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
    v = tf.get_variable("v", [1])
  return v

v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.

v1

<tf.Variable 'foo/v:0' shape=(1,) dtype=float32_ref>

## tf.constant_initializer

Initializer that generates tensors with constant values.

In [83]:
value = [0, 1, 2, 3, 4, 5, 6, 7]
#value = np.array(value)
#value = value.reshape([2, 4])
init = tf.constant_initializer(value)
print('fitting shape:')

tf.reset_default_graph()
with tf.Session():
    x = tf.get_variable('x', shape=[2, 4], initializer=init)
    x.initializer.run()
    print(x.eval())
    
tf.reset_default_graph()
print('larger shape:')
with tf.Session():
    x = tf.get_variable('x', shape=[3, 4], initializer=init)
    x.initializer.run()
    print(x.eval())
    
tf.reset_default_graph()
print('smaller shape:')
with tf.Session():
    x = tf.get_variable('x', shape=[2, 3], initializer=init)


fitting shape:
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]
larger shape:
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]
 [7. 7. 7. 7.]]
smaller shape:


ValueError: Too many elements provided. Needed at most 6, but received 8

## tf.random_normal_initializer

Initializer that generates tensors with a normal distribution.

In [91]:
b_init = tf.random_normal_initializer(mean=1,stddev=1)

tf.reset_default_graph()
with tf.Session() as sess:
    x = tf.get_variable('x', shape=[3, 4], initializer=b_init)
    sess.run(x.initializer)
    print(x.eval())

[[ 1.2087301   0.77924216  0.720313   -0.3026396 ]
 [ 1.5413682   2.71505    -0.25349855  0.80202156]
 [ 1.5633167   1.0423821   2.014656    0.4991575 ]]


## tf.equal

Returns the truth value of (x == y) element-wise.

In [101]:
b3 = tf.Variable(tf.random_normal([3,4]))
b4 = tf.Variable(tf.ones([3,4]))
b5 = tf.Variable(tf.ones([3,4]))
x=tf.equal(b3,b4)
y=tf.equal(b4,b5)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b3))
    print(sess.run(b4))
    print(sess.run(b4))
    print(sess.run(x))
    print(sess.run(y))

[[ 0.5720199  -1.0653263  -0.8307145  -0.23721945]
 [ 0.1217366   0.11875598  0.16571249 -1.217284  ]
 [-1.7476516   0.88212657  0.21615282 -0.02204372]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## tf.matmul

Multiplies matrix a by matrix b, producing a * b.

In [41]:
matrix3 = tf.constant([[2, 3]]) 
matrix4 = tf.constant([[5],[2]]) 
product2 = tf.matmul(matrix3,matrix4)

with tf.Session() as sess:
    print(sess.run(product))
    

[[16]]
